parserOptions:
  ecmaVersion: 2017
  sourceType: module
plugins:
  - wdio
env:
  browser: true
  node: true
extends: 'plugin:wdio/recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 1
  eol-last:
    - error
